version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pbl_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db 
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: password
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: ${APP_URL:-http://103.139.192.54:8080}
      ASSET_URL: ${APP_URL:-http://103.139.192.54:8080}
      FORCE_HTTPS: ${FORCE_HTTPS:-false}

  db:
    image: mysql:8.0
    container_name: pbl_db
    restart: unless-stopped
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: