export enum FormType {
    DATA_PRIBADI = 'DATA_PRIBADI',
    PENDIDIKAN = 'PENDIDIKAN',
    PENGALAMAN = 'PENGALAMAN',
    ORGANISASI = 'ORGANISASI',
    PRESTASI = 'PRESTASI',
    SOCIAL_MEDIA = 'SOCIAL_MEDIA',
    DATA_TAMBAHAN = 'DATA_TAMBAHAN'
}